name: table_calendar
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 2.2.3
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: